plugins {
    id 'com.android.application'
}

def ksPath = System.getenv("KEYSTORE_PATH")
def ksStorePass = System.getenv("STORE_PASS")
def ksKeyPass = System.getenv("KEY_PASS")
def ksAlias = System.getenv("KEY_ALIAS")

android {
    namespace 'com.fx991cnx.fang'
    compileSdk 34

    defaultConfig {
        applicationId "com.fx991cnx.fang"
        minSdk 24
        targetSdk 34
        versionCode 8
        versionName "1.0.8"
    }

    signingConfigs {
        release {
            if (ksPath != null && ksStorePass != null && ksKeyPass != null && ksAlias != null) {
                storeFile file(ksPath)
                storePassword ksStorePass
                keyAlias ksAlias
                keyPassword ksKeyPass
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (ksPath != null) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
